# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('question', models.CharField(max_length=64)),
                ('choiceA', models.CharField(max_length=32)),
                ('choiceB', models.CharField(max_length=32)),
                ('choiceC', models.CharField(max_length=32)),
                ('choiceD', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=32)),
            ],
        ),
    ]
