# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64)),
                ('questionid', models.IntegerField()),
                ('useranswer', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
