# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190313_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlib',
            name='choiceA',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='choiceB',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='choiceC',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='choiceD',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='question',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
