# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190524_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathUser',
            fields=[
                ('openid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
    ]
