# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_erroranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=64)),
                ('questionid', models.IntegerField()),
                ('useranswer', models.CharField(max_length=128)),
                ('trueanswer', models.CharField(max_length=128)),
                ('qs', models.CharField(max_length=512)),
            ],
        ),
    ]
