# Generated by Django 2.1.7 on 2019-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=100)),
                ('gotime', models.CharField(max_length=32)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('peoplenum', models.CharField(max_length=3)),
                ('addtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
