# Generated by Django 2.1.7 on 2019-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpinpin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinUser',
            fields=[
                ('openid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
    ]
