# Generated by Django 2.1.7 on 2019-03-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpinpin', '0002_pinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pininformation',
            name='sortgotime',
            field=models.IntegerField(default=2, verbose_name=2),
            preserve_default=False,
        ),
    ]
